import type { IncomingMessage, Server as HttpServer } from "http";
import type { Duplex } from "stream";
import { WebSocket, WebSocketServer, type RawData } from "ws";
import { createServerLogger, normalizeError } from "@/lib/logger";
import { isValidPlivoStreamToken } from "@/lib/plivo-stream-auth";
import { PlivoStreamGateway } from "@/providers/telephony/plivo-stream.gateway";
import { canAcceptMediaStreams } from "./media-lifecycle";
const log = createServerLogger("plivo-websocket"); const servers = new WeakMap<HttpServer, WebSocketServer>();
export function initializePlivoWebSocket(server: HttpServer): WebSocketServer { const existing = servers.get(server); if (existing) return existing; const socketServer = new WebSocketServer({ noServer: true, perMessageDeflate: false, clientTracking: true }); servers.set(server, socketServer); server.on("upgrade", (request: IncomingMessage, socket: Duplex, head: Buffer) => { const url = new URL(request.url ?? "/", "http://localhost"); if (url.pathname !== "/api/plivo/stream") return; const callId = url.searchParams.get("callId")?.trim() ?? ""; if (!canAcceptMediaStreams()) return reject(socket, 503, "Media server is draining"); if (!isValidPlivoStreamToken(callId, url.searchParams.get("token"))) { log.warn({ event: "plivo.media.upgrade_rejected", reason: "authentication_failed" }, "Plivo media authentication rejected"); return reject(socket, 403, "Forbidden"); } socketServer.handleUpgrade(request, socket, head, webSocket => socketServer.emit("connection", webSocket, request, callId)); }); socketServer.on("connection", (socket: WebSocket, _request: IncomingMessage, callId: string) => { log.info({ event: "plivo.stream.connected", internalCallId: callId }, "Authenticated Plivo stream connected"); let chain = Promise.resolve(); socket.on("message", (data: RawData) => { chain = chain.then(() => PlivoStreamGateway.handle(socket, raw(data), callId)).catch(error => log.error({ event: "plivo.media.failed", error: normalizeError(error) }, "Plivo media message failed")); }); socket.on("close", (code: number, reason: Buffer) => { void PlivoStreamGateway.close(socket, code, reason.toString("utf8")).catch(error => log.error({ event: "plivo.stream.close_cleanup_failed", internalCallId: callId, closeCode: code, error: normalizeError(error) }, "Plivo stream close cleanup failed")); }); }); server.once("close", () => { servers.delete(server); socketServer.close(); }); return socketServer; }
function raw(data: RawData): string { return Buffer.isBuffer(data) ? data.toString("utf8") : Array.isArray(data) ? Buffer.concat(data).toString("utf8") : Buffer.from(data).toString("utf8"); }
function reject(socket: Duplex, status: number, message: string): void { socket.write(`HTTP/1.1 ${status} ${message}\r\nConnection: close\r\n\r\n`); socket.destroy(); }
